/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowUploadRouteImport } from './routes/flow.upload'
import { Route as FlowSummaryRouteImport } from './routes/flow.summary'
import { Route as FlowPrintingRouteImport } from './routes/flow.printing'
import { Route as FlowConfigureRouteImport } from './routes/flow.configure'
import { Route as FlowCompletedRouteImport } from './routes/flow.completed'

const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowUploadRoute = FlowUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => FlowRoute,
} as any)
const FlowSummaryRoute = FlowSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => FlowRoute,
} as any)
const FlowPrintingRoute = FlowPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => FlowRoute,
} as any)
const FlowConfigureRoute = FlowConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => FlowRoute,
} as any)
const FlowCompletedRoute = FlowCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => FlowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow': typeof FlowRouteWithChildren
  '/flow/completed': typeof FlowCompletedRoute
  '/flow/configure': typeof FlowConfigureRoute
  '/flow/printing': typeof FlowPrintingRoute
  '/flow/summary': typeof FlowSummaryRoute
  '/flow/upload': typeof FlowUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow': typeof FlowRouteWithChildren
  '/flow/completed': typeof FlowCompletedRoute
  '/flow/configure': typeof FlowConfigureRoute
  '/flow/printing': typeof FlowPrintingRoute
  '/flow/summary': typeof FlowSummaryRoute
  '/flow/upload': typeof FlowUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flow': typeof FlowRouteWithChildren
  '/flow/completed': typeof FlowCompletedRoute
  '/flow/configure': typeof FlowConfigureRoute
  '/flow/printing': typeof FlowPrintingRoute
  '/flow/summary': typeof FlowSummaryRoute
  '/flow/upload': typeof FlowUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flow'
    | '/flow/completed'
    | '/flow/configure'
    | '/flow/printing'
    | '/flow/summary'
    | '/flow/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flow'
    | '/flow/completed'
    | '/flow/configure'
    | '/flow/printing'
    | '/flow/summary'
    | '/flow/upload'
  id:
    | '__root__'
    | '/'
    | '/flow'
    | '/flow/completed'
    | '/flow/configure'
    | '/flow/printing'
    | '/flow/summary'
    | '/flow/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowRoute: typeof FlowRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/upload': {
      id: '/flow/upload'
      path: '/upload'
      fullPath: '/flow/upload'
      preLoaderRoute: typeof FlowUploadRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/summary': {
      id: '/flow/summary'
      path: '/summary'
      fullPath: '/flow/summary'
      preLoaderRoute: typeof FlowSummaryRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/printing': {
      id: '/flow/printing'
      path: '/printing'
      fullPath: '/flow/printing'
      preLoaderRoute: typeof FlowPrintingRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/configure': {
      id: '/flow/configure'
      path: '/configure'
      fullPath: '/flow/configure'
      preLoaderRoute: typeof FlowConfigureRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/completed': {
      id: '/flow/completed'
      path: '/completed'
      fullPath: '/flow/completed'
      preLoaderRoute: typeof FlowCompletedRouteImport
      parentRoute: typeof FlowRoute
    }
  }
}

interface FlowRouteChildren {
  FlowCompletedRoute: typeof FlowCompletedRoute
  FlowConfigureRoute: typeof FlowConfigureRoute
  FlowPrintingRoute: typeof FlowPrintingRoute
  FlowSummaryRoute: typeof FlowSummaryRoute
  FlowUploadRoute: typeof FlowUploadRoute
}

const FlowRouteChildren: FlowRouteChildren = {
  FlowCompletedRoute: FlowCompletedRoute,
  FlowConfigureRoute: FlowConfigureRoute,
  FlowPrintingRoute: FlowPrintingRoute,
  FlowSummaryRoute: FlowSummaryRoute,
  FlowUploadRoute: FlowUploadRoute,
}

const FlowRouteWithChildren = FlowRoute._addFileChildren(FlowRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowRoute: FlowRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
